package com.sb.problems.strings;

public class SearchSubstringInString {
    public static void main(String[] args) {
        SearchSubstringInString obj = new SearchSubstringInString();
        System.out.println(obj.strStr("abc", "bc"));
        System.out.println(obj.strStr("GeeksForGeeks", "Fr"));
        System.out.println(obj.strStr("GeeksForGeeks", "For"));
        System.out.println(obj.strStr("For", "GeeksForGeeks"));
        System.out.println(obj.strStr("For", ""));
        System.out.println(obj.strStr("", ""));
        System.out.println(obj.strStr("ABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZ1ABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZABCDEFGHIJKLMNOPQURSUVWXYZ", "ABCDEFGHIJKLMNOPQURSUVWXYZ1"));
        System.out.println(obj.strStr("FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF", "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE"));
    }

    private int strStr(String A, String B) {
        if(B.length() > A.length() || A.length() == 0 || B.length() == 0) {
            return -1;
        }
        char[] aChars = A.toCharArray();
        char[] bChars = B.toCharArray();
        for(int i=0; i< A.length(); i++) {
            boolean substrFound = true;
            if(aChars[i] == bChars[0]) {
                if(i+bChars.length <= aChars.length) {
                    for(int j = 1; j < bChars.length; j++) {
                        if(aChars[i+j] != bChars[j]) {
                            substrFound = false;
                            break;
                        }
                    }
                    if(substrFound) {
                        return i;
                    }
                }
            }
        }
        return -1;
    }
}
